apiVersion: v1
kind: Template
metadata:
  name: galera
objects:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: "galera"
  spec:
    serviceName: "galera"
    replicas: 3
    template:
      metadata:
        labels:
          name: "galera"
      spec:
        containers:
          - name: mariadb-container
            image: "registry.access.redhat.com/rhscl/galera-32-rhel7:3.2"
            resources:
              requests:
                memory: 128Mi
                cpu: 250m
              limits:
                memory: 512Mi
                cpu: 500m
            ports:
              - containerPort: 27017
            args:
              - "run-mongod-replication"
            volumeMounts:
              - name: galera-data
                mountPath: "/var/lib/galera/data"
            env:
              - name: galera_DATABASE
                valueFrom:
                  configMapKeyRef:
                    key: database-name
                    name: galera-configmap
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: galera-data
          labels:
            name: "galera"
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: 5Gi
- apiVersion: v1
  kind: Service
  metadata:
    name: galera
    labels:
      name: "galera"
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  spec:
    clusterIP: None
    ports:
      - name: galera
        port: 3306
    selector:
      name: "galera"
